---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: games-db
spec:
  version: "11.2"
  storageType: Durable
  replicas: 3
  standbyMode: Hot
  storage:
    storageClassName: do-block-storage
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
  terminationPolicy: DoNotTerminate
  updateStrategy:
    type: RollingUpdate
  podTemplate:
    spec:
      env:
      - name: POSTGRES_DB
        value: kondo-games
  monitor:
    agent: prometheus.io/builtin
    prometheus:
      port: 56790
