"""empty message

Revision ID: dc43ea8fac97
Revises: 
Create Date: 2020-04-04 12:19:12.703787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dc43ea8fac97"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_title",
        sa.Column("game_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("steam_app_id", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("game_id"),
    )
    op.create_table(
        "game_session",
        sa.Column("session_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("game_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("slots", sa.Integer(), nullable=True),
        sa.Column("time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("host", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["game_id"], ["game_title.game_id"],),
        sa.PrimaryKeyConstraint("session_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("game_session")
    op.drop_table("game_title")
    # ### end Alembic commands ###
