---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: kondogg/auth
        imagePullPolicy: Always
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        envFrom:
        - configMapRef:
            name: kondo-common
        env:
        - name: DISCORD_CLIENT_ID
          value: /etc/discord/client-id
        - name: DISCORD_CLIENT_SECRET
          value: /etc/discord/client-secret
        volumeMounts:
        - name: discord-creds
          mountPath: /etc/discord
        ports:
        - name: http
          containerPort: 8000
      volumes:
      - name: discord-creds
        secret:
          secretName: discord-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 8000
    targetPort: http
